service: jotbox-app-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: create.main
    events:
      - http:
          path: drafts
          method: post
          cors: true
          authorizer: aws_iam
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
      handler: get.main
      events:
      - http:
          path: drafts/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
      handler: list.main
      events:
      - http:
          path: drafts
          method: get
          cors: true
          authorizer: aws_iam
  update:
      handler: update.main
      events:
      - http:
          path: drafts/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
      handler: delete.main
      events:
      - http:
          path: drafts/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  addUser:
      handler: addUser.main
      events:
      - http:
          path: users
          method: post
          cors: true
          authorizer: aws_iam
  listUsers:
      handler: listUsers.main
      events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: aws_iam
  addGenre:
      handler: addGenre.main
      events:
      - http:
          path: genres
          method: post
          cors: true
          authorizer: aws_iam
  getGenres:
      handler: getGenres.main
      events:
      - http:
          path: genres
          method: get
          cors: true
          authorizer: aws_iam
  listGenres:
      handler: listGenres.main
      events:
      - http:
          path: genres/list
          method: get
          cors: true
          authorizer: aws_iam
  viewDrafts:
      handler: viewDrafts.main
      events:
      - http:
          path: users/{id}
          method: get
          cors: true
          authorizer: aws_iam